### ISSUE TITLE
Как получить "Период для получения оценок в unixtime"?

### ISSUE THREAD

**Issue by HaR00ke** [Bs0Dd/KunAPIPy#1]
Не особо понимаю что такое "Период для получения оценок в unixtime"
Как и где его взять?

**Comment by HaR00ke** [comment]
+Почему этот параметр называется период если оно принимает только ОДНУ ДАТУ?!??!?
А период это время между ДВУМЯ датами

**Comment by HaR00ke** [comment]
Короче, разобрался в самом API кунделика (api.kundelik.kz)
В этой либе нет некоторых функций которые есть в апи самого кунделика

**Comment by Bs0Dd** [comment]
Увы, библиотека с 20 года подзаброшена. А докуменация как и основа взята из [DnevnikRuAPI](https://github.com/kesha1225/DnevnikRuAPI). Возможно я займусь реорганизацией и актуализацией библиотеки, но увы, времени пока не хватает.

**Comment by haroke4** [comment]
thanks!
